version: '3'
services:
  apachephp:
    build:
      context: ./
      dockerfile: ApachePhp.DockerFile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./html/:/var/www/html/"
  devmysql:
    build:
      context: ./
      dockerfile: MySQLDev.DockerFile
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD : 'yes'
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
